dist: xenial
language: python
notifications:
  email:
    on_failure: change
    on_succes: never
python:
- '3.5'
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
#- pytest --cov=./cffconvert --cov-report=xml test/
#- pytest livetest/
- sonar-scanner
sudo: false
