--- 
dist: xenial
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
python: 
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script: 
    # run the unit tests, with test coverage calculation
  - "pytest --cov=./cffconvert --cov-report=xml test/"
    # also run the live tests, without test coverage calculation
  - "pytest livetest/"
sudo: false
